"""
Slack API Integration
Sends messages and daily briefs to Slack channels
"""

from slack_sdk import WebClient
from slack_sdk.errors import SlackApiError
from datetime import datetime
import os


class SlackClient:
    def __init__(self, token=None, channel=None):
        self.token = token or os.getenv("SLACK_BOT_TOKEN")
        self.channel = channel or os.getenv("SLACK_CHANNEL_ID", "#general")

        if not self.token:
            raise ValueError("SLACK_BOT_TOKEN environment variable not set")

        self.client = WebClient(token=self.token)

    def send_message(self, text: str, channel: str = None):
        """Send a message to Slack"""
        try:
            response = self.client.chat_postMessage(
                channel=channel or self.channel,
                text=text
            )
            return response["ts"]  # Message timestamp
        except SlackApiError as e:
            print(f"Slack error: {e.response['error']}")
            raise

    def send_daily_brief(self):
        """Generate and send a daily brief"""
        # TODO: Get real activity from context store
        # For now, use placeholder data

        brief = f"""📊 *Daily Brief - {datetime.now().strftime('%B %d, %Y')}*

*Tasks Completed Today:* 3
*Calendar Events:* 2 meetings scheduled
*Watch Messages:* 5 voice commands processed

*Recent Activity:*
• Calendar event created: "Meeting with John"
• Context saved: "Project timeline discussion"
• System status: All agents operational

_Generated by Agent Swarm via Galaxy Watch 4_
"""
        return self.send_message(brief)

    def send_context_notification(self, context_text: str):
        """Send notification when a context is saved"""
        message = f"💾 *Context Saved*\n\n{context_text}\n\n_Via Galaxy Watch 4_"
        return self.send_message(message)


# Singleton instance
_slack_client = None


def get_slack_client():
    """Get or create Slack client singleton"""
    global _slack_client
    if _slack_client is None:
        _slack_client = SlackClient()
    return _slack_client
